import type { EventRecord } from './types';

const SEED_CREATED_AT = '2026-05-22T08:00:00.000Z';

export const seedEvents: EventRecord[] = [
  {
    id: 'seed-event-2026-01',
    title: 'Talk IA Generative: du prototype au produit',
    description: 'Conférence sur les bonnes pratiques pour transformer un prototype IA en solution utilisable sur campus.',
    category: 'Talk',
    startDateTime: '2026-05-23T09:00:00.000Z',
    endDateTime: '2026-05-23T10:30:00.000Z',
    locationName: 'Amphi Ibn Khaldoun',
    locationAddress: 'Campus Principal - Bloc A',
    organizerName: 'École d Ingénierie Logicielle',
    capacity: 180,
    registeredCount: 74,
    tags: ['AI', 'LLM', 'Product', 'Innovation'],
    createdAt: SEED_CREATED_AT,
  },
  {
    id: 'seed-event-2026-02',
    title: 'Workshop React Native + Expo Router',
    description: 'Atelier pratique pour construire une application mobile multi-routes avec navigation et état local.',
    category: 'Workshop',
    startDateTime: '2026-05-23T13:30:00.000Z',
    endDateTime: '2026-05-23T16:30:00.000Z',
    locationName: 'Lab Mobile 2',
    locationAddress: 'Campus Principal - Bâtiment Informatique',
    organizerName: 'Département Informatique',
    capacity: 36,
    registeredCount: 22,
    tags: ['React', 'Expo', 'Mobile', 'TypeScript'],
    createdAt: SEED_CREATED_AT,
  },
  {
    id: 'seed-event-2026-03',
    title: 'Club Data Science: session projets',
    description: 'Rencontre du club autour des projets étudiants en data science et visualisation.',
    category: 'Club',
    startDateTime: '2026-05-24T17:00:00.000Z',
    endDateTime: '2026-05-24T19:00:00.000Z',
    locationName: 'Maison des Étudiants',
    locationAddress: 'Aile Est - Salle Club 4',
    organizerName: 'Club Data Science Campus',
    capacity: 45,
    registeredCount: 18,
    tags: ['Data', 'Python', 'Visualization', 'Community'],
    createdAt: SEED_CREATED_AT,
  },
  {
    id: 'seed-event-2026-04',
    title: 'Exam Blanc: Algorithmique et Complexité',
    description: 'Simulation d examen avec correction guidée pour préparer l évaluation finale.',
    category: 'Exam',
    startDateTime: '2026-05-25T08:30:00.000Z',
    endDateTime: '2026-05-25T10:30:00.000Z',
    locationName: 'Salle 204',
    locationAddress: 'Faculté des Sciences - Niveau 2',
    organizerName: 'Pôle Pédagogique',
    capacity: 60,
    registeredCount: 60,
    tags: ['Exam', 'Algorithms', 'Prep', 'CS'],
    createdAt: SEED_CREATED_AT,
  },
  {
    id: 'seed-event-2026-05',
    title: 'Talk Carriere Tech: CV, portfolio et entretien',
    description: 'Conseils concrets par des recruteurs pour améliorer candidature et posture en entretien.',
    category: 'Talk',
    startDateTime: '2026-05-26T14:00:00.000Z',
    endDateTime: '2026-05-26T15:15:00.000Z',
    locationName: 'Amphi Al Khawarizmi',
    locationAddress: 'Campus Innovation - Bloc C',
    organizerName: 'Cellule Insertion Professionnelle',
    capacity: 200,
    registeredCount: 119,
    tags: ['Career', 'Interview', 'Portfolio', 'SoftSkills'],
    createdAt: SEED_CREATED_AT,
  },
  {
    id: 'seed-event-2026-06',
    title: 'Workshop MLOps: deployer un modele avec API',
    description: 'Mise en pratique de la chaine MLOps: versioning, inference API et supervision.',
    category: 'Workshop',
    startDateTime: '2026-05-27T09:30:00.000Z',
    endDateTime: '2026-05-27T12:30:00.000Z',
    locationName: 'Lab Data 1',
    locationAddress: 'Centre de Recherche Numerique',
    organizerName: 'Laboratoire IA Appliquee',
    capacity: 32,
    registeredCount: 29,
    tags: ['AI', 'MLOps', 'API', 'Data'],
    createdAt: SEED_CREATED_AT,
  },
  {
    id: 'seed-event-2026-07',
    title: 'Club Cybersecurity: CTF debutant',
    description: 'Session encadree du club securite pour apprendre les bases du CTF en equipe.',
    category: 'Club',
    startDateTime: '2026-05-28T16:00:00.000Z',
    endDateTime: '2026-05-28T18:00:00.000Z',
    locationName: 'Salle Reseaux 5',
    locationAddress: 'Institut Tech - Etage 1',
    organizerName: 'Club Cyber Campus',
    capacity: 30,
    registeredCount: 17,
    tags: ['Security', 'CTF', 'Networking', 'Teamwork'],
    createdAt: SEED_CREATED_AT,
  },
  {
    id: 'seed-event-2026-08',
    title: 'Journee Orientation Masters',
    description: 'Rencontre avec les responsables de filieres master et anciens laureats.',
    category: 'Other',
    startDateTime: '2026-05-29T10:00:00.000Z',
    endDateTime: '2026-05-29T13:00:00.000Z',
    locationName: 'Hall Principal',
    locationAddress: 'Campus Central',
    organizerName: 'Direction des Etudes',
    capacity: 250,
    registeredCount: 96,
    tags: ['Orientation', 'Master', 'Studies', 'Networking'],
    createdAt: SEED_CREATED_AT,
  },
  {
    id: 'seed-event-2026-09',
    title: 'Exam Anglais Technique',
    description: 'Evaluation des competences en anglais applique aux contextes scientifiques et numeriques.',
    category: 'Exam',
    startDateTime: '2026-05-30T08:00:00.000Z',
    endDateTime: '2026-05-30T10:00:00.000Z',
    locationName: 'Bloc Langues - Salle 12',
    locationAddress: 'Campus Lettres et Sciences Humaines',
    organizerName: 'Departement Langues',
    capacity: 90,
    registeredCount: 53,
    tags: ['Exam', 'English', 'Communication', 'Assessment'],
    createdAt: SEED_CREATED_AT,
  },
];